config/routes.rb
Rails.application.routes.draw do

  resources :places do
    post 'add_to_visited', on: :member
  end

  resources :events

  resource :calendar, only: [:show], controller: :calendar

  devise_for :users

  resources :pets

  resources :home, only: [:show], controller: :home

  resources :charges

  resources :messages

  root 'home#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true
  
  def life_time
    (Date.today - date_of_birth).to_i
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  expose_decorated(:pet, attributes: :pet_params)
  expose_decorated(:pets)
  #before_action :authenticate_user!
  before_action :check_owner, only: [:edit, :destroy]

  def create
    pet = Pet.new(pet_params)
    pet.user = current_user
    respond_to do |format|
      if pet.save
        format.html { redirect_to pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: pet }
      else
        format.html { render :new }
        format.json { render json: pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if pet.update(pet_params)
        format.html { redirect_to pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: pet }
      else
        format.html { render :edit }
        format.json { render json: pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :date_of_birth)
    end

    def check_owner
      if pet.user != current_user
        redirect_to root_path, notice: 'This is not your pet!'
      end
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.haml
= form_for(pet) do |f|
  - if pet.errors.any?
    #error_explanation
      %h2
        = pluralize(pet.errors.count, "error")
        prohibited this pet from being saved:
      %ul
        - pet.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :date_of_birth
    %br/
    = f.date_select :date_of_birth
  .actions
    = f.submit

app/views/pets/edit.html.haml
%h1 Editing pet
= render 'form'
= link_to 'Show', pet
|
\#{link_to 'Back', pets_path}

app/views/pets/index.html.haml
%h1 My pets
%table.table
  %tr
    %th Name
    %th Date of birth
    %th{:colspan => "3"} Options
    %th Life time

  - current_user.pets.each do |pet|
    %tr
      %td= pet.name
      %td= pet.date_of_birth
      %td= link_to 'Show', pet, class: 'btn btn-primary btn-sm'
      %td= link_to 'Edit', edit_pet_path(pet), class: 'btn btn-warning btn-sm'
      %td= link_to 'Remove', pet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
      %td= "Today I have " + pluralize(pet.life_time, 'day')
%br/
= link_to 'Add New Pet', new_pet_path, class: 'btn btn-success'

app/views/pets/new.html.haml
%h1 New pet
= render 'form'
= link_to 'Back', pets_path

app/views/pets/show.html.haml
%p
  %strong Name:
  = pet.name
%p
  %strong Date of birth:
  = pet.date_of_birth
= link_to 'Edit', edit_pet_path(pet)
|
\#{link_to 'Back', pets_path}