config/routes.rb
Rails.application.routes.draw do

  resources :places do
    post 'add_to_visited', on: :member
  end

  resources :events

  resource :calendar, only: [:show], controller: :calendar

  devise_for :users

  resources :pets

  resources :home, only: [:show], controller: :home

  resources :charges

  resources :messages

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :pet

  validates :title, :pet_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  expose(:event)
  expose(:events)
  expose(:pet)
  before_action :authenticate_user!
  
  def create
    event = Event.new(event_params)
    event.user = current_user
    respond_to do |format|
      if event.save
        format.html { redirect_to event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: event }
      else
        format.html { render :new }
        format.json { render json: event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if event.update(event_params)
        format.html { redirect_to event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: event }
      else
        format.html { render :edit }
        format.json { render json: event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render :show }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :date, :time, :pet_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for(event) do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.input :date, :as => :date_picker
  = f.input :time, :as => :time_picker
  = f.input :pet_id, collection: current_user.pets, include_blank: false
  = f.button :submit

app/views/events/edit.html.haml
%h1
  Editing event

= render 'form'

= link_to 'Show', event |
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events
%table
  %thead
    %tr
      %th Title
      %th Description
      %th Event date
      %th{:colspan => "3"}
  %tbody
    - events.each do |event|
      %tr
        %td= event.title
        %td= event.description
        %td= event.date
        %td= event.time.strftime("%H:%m")
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

app/views/events/show.html.haml
%p
  %strong
    Title:
  = event.title


%p
  %strong
    Description:
  = event.description


%p
  %strong
    Event date:
  = event.date

%p
  %strong
    Event time:
  = event.time.strftime("%H:%m") if event.time.present?


= link_to 'Edit', edit_event_path(event)
= link_to 'Back', events_path