config/routes.rb
Rails.application.routes.draw do

  resources :places do
    post 'add_to_visited', on: :member
  end

  resources :events

  resource :calendar, only: [:show], controller: :calendar

  devise_for :users

  resources :pets

  resources :home, only: [:show], controller: :home

  resources :charges

  resources :messages

  root 'home#index'

end

app/models/place.rb
class Place < ActiveRecord::Base

  has_many :place_users
  has_many :users, through: :place_users

  geocoded_by :address
  after_validation :geocode

  def address
    [street, city, country].compact.join(', ')
  end

  def visited? (user)
    if self.users.find_by id: user
      return true
    else
      return false
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :premium_user?, only: [:create]

  expose(:users)
  expose(:user)
  expose_decorated(:places)
  expose_decorated(:place)
  respond_to :html

  def create
    place = Place.new(place_params)
    place.save
    respond_with(place)
  end

  def update
    place.update(place_params)
    respond_with(place)
  end

  def destroy
    place.destroy
    respond_with(place)
  end

  def add_to_visited
    begin
      current_user.places << place
      notice = 'Place added to visited'
    rescue ActiveRecord::RecordInvalid
      notice = "You can't mark place as visited twice"
    ensure
      redirect_to place_path, notice: notice
    end
  end

  private

    def premium_user?
      unless current_user.has_premium_account?
        redirect_to new_charge_path
        flash[:error] = "You aren't a premium user!"
      end
    end

    def place_params
      params.require(:place).permit(:name, :street, :city, :country, :description)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.haml
= simple_form_for(place) do |f|
  = f.input :name
  = f.input :street
  = f.input :city
  = f.input :country
  = f.input :description, as: :text
  = f.button :submit

app/views/places/_maps.html.erb
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= place.latitude %>,
        "lng": <%= place.longitude %>,
        "picture": {
          "url": "http://i.share.pho.to/fa012c40_o.png",
          "width":  36,
          "height": 36
        },
        "infowindow": 'Wow, so cool, wow, doge happy!',
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
  });
</script>

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 List of nice places

%table.table.table-bordered
  %thead
    %tr
      %th Street
      %th City
      %th Country
      %th Options
      %th Visited?

  %tbody
    - places.each do |place|
      %tr
        %td= place.street
        %td= place.city
        %td= place.country
        %td= link_to 'Show details', place, class: 'btn btn-success btn-sm'
        %td= place.visited_state(current_user.id)
%br
- if current_user.has_premium_account?
  = link_to 'Add new place', new_place_path, class: 'btn btn-success btn-sm'

app/views/places/new.html.haml
%h1 New place

= render 'form'

app/views/places/show.html.haml
.col-md-3
  %h3= place.name

  %p
    %b Street:
    = place.street
  %p
    %b City:
    = place.city
  %p
    %b Country:
    = place.country
  %p
    %b Description:
    = place.description

  = link_to 'Add to visited', add_to_visited_place_path, method: :post, class: 'btn btn-primary btn-lg'
  %br/
.col-md-1
.col-md-8
  %h3 Map
  %div{:style => "width: 600px;"}
    #map{:style => "width: 600px; height: 400px;"}
    = render 'places/maps'