config/routes.rb
Rails.application.routes.draw do

  resources :places do
    post 'add_to_visited', on: :member
  end

  resources :events

  resource :calendar, only: [:show], controller: :calendar

  devise_for :users

  resources :pets

  resources :home, only: [:show], controller: :home

  resources :charges

  resources :messages

  root 'home#index'

end

app/views/layouts/_header.html.haml
.navbar
  .container
    %ul
      - if user_signed_in?
        %li.navbar-btn= link_to 'calendar', calendar_path
        %li.navbar-btn= link_to 'new event', new_event_path
        %li.navbar-btn= link_to 'my pets', pets_path
        %li.navbar-btn= link_to 'places', places_path
        %li.navbar-btn= link_to "Hello, #{current_user.email}", edit_user_registration_path
        %li.navbar-btn= link_to 'My Profile', edit_user_registration_path
        %li.navbar-btn= link_to 'sign out', destroy_user_session_path, method: :delete
      - else
        %li.navbar-btn= link_to 'sign in', new_user_session_path
        %li.navbar-btn= link_to 'sign up', new_user_registration_path

app/views/layouts/_messages.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title GiveMeFood
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all"
    = javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js"
    = javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry"
    = javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/messages'
      %div#content
        = yield